### ISSUE TITLE
Incomplete xml?

### ISSUE THREAD

**Issue by MrHappy** [elmerohueso/3DS_Game_Server#2]
Some cia's don't get resolved in 3dsreleases.xml.
It appears the json-files [here](https://github.com/hax0kartik/3dsdb/tree/master/jsons) are containing the cia's missing from 3dsreleases.xml.
Is it possible to have the script check against both files?
If so, how?

**Comment by elmerohueso** [comment]
I'm no longer using this (kids lost the 3DS), but you should be able to reformat the missing entries to XML and merge them.

**Comment by MrHappy** [comment]
Thanks for responding.
